### ISSUE TITLE
May I have the  link to the dataset?

### ISSUE THREAD

**Issue by asd08573064** [ricbl/eyetracking#1]
Hello, 
I've recently been working on image captioning on CXR, and I found this project helpful.
May you please send me the link?
Thank you so much.

**Comment by ricbl** [comment]
Thank you for your interest in this dataset. We are in the final stages of preparing the dataset for submission, and it should be available in the upcoming weeks.

**Comment by asd08573064** [comment]
Thank you so much. Appreciate your great work!

**Comment by ricbl** [comment]
Here it is: https://physionet.org/content/reflacx-xray-localization/1.0.0/

**Comment by asd08573064** [comment]
Thank you so much!
